### ISSUE TITLE
6.4.72 Cron error ArgumentCountError in entity.php

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#491]
Got these e-mails with errors from a groupoffice "cron job"
They appeared after the update to I think 6.4.71

Subject: Cron <www-data@XX> php /usr/share/groupoffice/cron.php /etc/groupoffice/config.php
Body:
ArgumentCountError in /usr/share/groupoffice/go/core/orm/Entity.php at line 303: Too few arguments to function go\core\orm\Entity::delete(), 0 passed in /usr/share/groupoffice/go/core/cron/GarbageCollection.php on line 43 and exactly 1 expected at 2019-11-04T08:00:01+00:00

**Comment by rasos** [comment]
Same here after upgrade to 6.4.72 yesterday (probably skipped 6.4.71).

**Comment by mschering** [comment]
Fixed in the next release.
